USE [YorkSupport]
GO

/****** Object:  View [dbo].[VIEW_CHILLER_RPT_CON_APP_DATA]    Script Date: 10/28/2014 9:17:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VIEW_CHILLER_RPT_CON_APP_DATA]
AS
SELECT 
	[SERIAL_NUM],
	[GEAR_CODE],
	[CAPACITY],
	[ALT_CAPACITY],
	[REFRIGERANT],
	[EVAP_EWT],
	[EVAP_LWT],
	[EVAP_FLOW],
	[EVAP_PD],
	[EVAP_PD_UNIT],
	[EVAP_FLUID_TYPE],
	[EVAP_NUM_PASSES],
	[EVAP_FF],
	[EVAP_DWP],
	[EVAP_NOZZLE_IN],
	[EVAP_NOZZLE_OUT],
	[COND_EWT],
	[COND_LWT],
	[COND_FLOW],
	[COND_PD],
	[COND_PD_UNIT],
	[COND_FLUID],
	[COND_NUM_PASSES],
	[COND_FF],
	[COND_DWPE],
	[COND_NOZZLE_IN],
	[COND_NOZZLE_OUT],
	[VOLTS],
	[PHASE],
	[FREQ],
	[KW],
	[HP],
	[FLA],
	[LRA],
	[IRA],
	[OIL_PUMP_VOLTS],
	[OIL_PUMP_LFA],
	[EVAP_TUBE_NUM],
	[COND_TUBE_NUM],
	[UNIT_PART_NUM],
	[SYS_WIRING_NUM],
	[CONTROL_PNL_PRT_NUM],
	[SYS_PIPE_PRT_NUM],
	[MOTOR_PRT_NUM],
	[CPLNG_GUARD_PRT_NUM],
	[COMPRSSR_PRT_NUM],
	[COOLER_TOP_BILL],
	[COOLER_NZ_ARRGMT],
	[COND_TOP_BILL],
	[COND_NOZZLE],
	[STARTER_TYPE],
	[HOT_GAS]
FROM SD_SDD001E


GO

