USE [YorkSupport]
GO

/****** Object:  View [dbo].[VIEW_CHILLER_RPT_CON_WTY_CLAIM]    Script Date: 10/28/2014 9:18:29 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VIEW_CHILLER_RPT_CON_WTY_CLAIM]
AS
SELECT 
	[SD_NBR],
	[SERIAL_NUM],
	[COMPONENT_SERIAL_NBR],
	[CMS_CONTRACT_NBR],
	[CMS_MODEL_NBR],
	[CLAIM_DATE],
	[SHIP_DATE],
	[START_DATE],
	[SD_FAILURE_DATE],
	[FAILURE_COMPONENT_CODE],
	[FAILURE_DEFECT_CODE],
	[EW_START_DATE]
FROM [YorkSupport].[dbo].[jumbo_warranty_details]
GO

